# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:  ## ENVENTOS
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  # permite que eu execute manualmente meu workflow, nao vou usar agora

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI: # nome do JOB
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Action: Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./src
          # Path to the Dockerfile
          
          file: ./src/Dockerfile
          # List of metadata for an image
          
          push: true
          
          tags: |
            amandhaasil/rotten-potatoes:latest
            amandhaasil/rotten-potatoes:${github.run_number}
          # assim eu garanto que eu sempre tenho uma tag diferente
          
          
          
